// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000021Component } from './my.000021.component';

@NgModule({
  declarations: [
    My000021Component,
  ],
  imports: [CommonModule],
  exports: [
    My000021Component,
  ]
})
export class Module000021 { }
