// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000016Component } from './my.000016.component';

@NgModule({
  declarations: [
    My000016Component,
  ],
  imports: [CommonModule],
  exports: [
    My000016Component,
  ]
})
export class Module000016 { }
