// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000009Component } from './my.000009.component';

@NgModule({
  declarations: [
    My000009Component,
  ],
  imports: [CommonModule],
  exports: [
    My000009Component,
  ]
})
export class Module000009 { }
