// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000001Component } from './my.000001.component';

@NgModule({
  declarations: [
    My000001Component,
  ],
  imports: [CommonModule],
  exports: [
    My000001Component,
  ]
})
export class Module000001 { }
