// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000026Component } from './my.000026.component';

@NgModule({
  declarations: [
    My000026Component,
  ],
  imports: [CommonModule],
  exports: [
    My000026Component,
  ]
})
export class Module000026 { }
