// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000010Component } from './my.000010.component';

@NgModule({
  declarations: [
    My000010Component,
  ],
  imports: [CommonModule],
  exports: [
    My000010Component,
  ]
})
export class Module000010 { }
