// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000014Component } from './my.000014.component';

@NgModule({
  declarations: [
    My000014Component,
  ],
  imports: [CommonModule],
  exports: [
    My000014Component,
  ]
})
export class Module000014 { }
