// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000025Component } from './my.000025.component';

@NgModule({
  declarations: [
    My000025Component,
  ],
  imports: [CommonModule],
  exports: [
    My000025Component,
  ]
})
export class Module000025 { }
