// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000036Component } from './my.000036.component';

@NgModule({
  declarations: [
    My000036Component,
  ],
  imports: [CommonModule],
  exports: [
    My000036Component,
  ]
})
export class Module000036 { }
