// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000027Component } from './my.000027.component';

@NgModule({
  declarations: [
    My000027Component,
  ],
  imports: [CommonModule],
  exports: [
    My000027Component,
  ]
})
export class Module000027 { }
