// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000039Component } from './my.000039.component';

@NgModule({
  declarations: [
    My000039Component,
  ],
  imports: [CommonModule],
  exports: [
    My000039Component,
  ]
})
export class Module000039 { }
