// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000028Component } from './my.000028.component';

@NgModule({
  declarations: [
    My000028Component,
  ],
  imports: [CommonModule],
  exports: [
    My000028Component,
  ]
})
export class Module000028 { }
