// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000019Component } from './my.000019.component';

@NgModule({
  declarations: [
    My000019Component,
  ],
  imports: [CommonModule],
  exports: [
    My000019Component,
  ]
})
export class Module000019 { }
