// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000003Component } from './my.000003.component';

@NgModule({
  declarations: [
    My000003Component,
  ],
  imports: [CommonModule],
  exports: [
    My000003Component,
  ]
})
export class Module000003 { }
