// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000023Component } from './my.000023.component';

@NgModule({
  declarations: [
    My000023Component,
  ],
  imports: [CommonModule],
  exports: [
    My000023Component,
  ]
})
export class Module000023 { }
