// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000002Component } from './my.000002.component';

@NgModule({
  declarations: [
    My000002Component,
  ],
  imports: [CommonModule],
  exports: [
    My000002Component,
  ]
})
export class Module000002 { }
