// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000004Component } from './my.000004.component';

@NgModule({
  declarations: [
    My000004Component,
  ],
  imports: [CommonModule],
  exports: [
    My000004Component,
  ]
})
export class Module000004 { }
