// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000000Component } from './my.000000.component';

@NgModule({
  declarations: [
    My000000Component,
  ],
  imports: [CommonModule],
  exports: [
    My000000Component,
  ]
})
export class Module000000 { }
