// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000018Component } from './my.000018.component';

@NgModule({
  declarations: [
    My000018Component,
  ],
  imports: [CommonModule],
  exports: [
    My000018Component,
  ]
})
export class Module000018 { }
