// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000022Component } from './my.000022.component';

@NgModule({
  declarations: [
    My000022Component,
  ],
  imports: [CommonModule],
  exports: [
    My000022Component,
  ]
})
export class Module000022 { }
