// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000038Component } from './my.000038.component';

@NgModule({
  declarations: [
    My000038Component,
  ],
  imports: [CommonModule],
  exports: [
    My000038Component,
  ]
})
export class Module000038 { }
