// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000007Component } from './my.000007.component';

@NgModule({
  declarations: [
    My000007Component,
  ],
  imports: [CommonModule],
  exports: [
    My000007Component,
  ]
})
export class Module000007 { }
